version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - bidichk
    - durationcheck
    - errcheck
    - funlen
    - govet
    - inamedparam
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - perfsprint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    errcheck:
      check-type-assertions: true
    funlen:
      lines: 100
      statements: 50
      ignore-comments: true
    inamedparam:
      skip-single-param: true
    nakedret:
      max-func-lines: 0
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-no-explanation:
        - funlen
        - gocognit
        - lll
    perfsprint:
      strconcat: false
    revive:
      enable-all-rules: false
      rules:
        - name: receiver-naming
          severity: warning
          disabled: false
          exclude:
            - ""
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - godot
        source: (noinspection|TODO)
      - linters:
          - gocritic
        source: //noinspection
      - linters:
          - bodyclose
          - dupl
          - errcheck
          - funlen
          - goconst
          - gosec
          - lll
          - noctx
          - wrapcheck
        path: _test\.go
    paths:
      - core/genesis_alloc.go
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - core/genesis_alloc.go
      - third_party$
      - builtin$
      - examples$
